#use this script if your jhbuild sysdeps --install command is not working
#works awesome in fedora

sudo dnf install   libuuid-devel -y
sudo dnf install   flac-devel -y
sudo dnf install   speex-devel -y
sudo dnf install   flex -y
sudo dnf install   libtasn1-devel -y
sudo dnf install   libffi-devel -y
sudo dnf install   libXt-devel -y
sudo dnf install   python3-cairo-devel -y
sudo dnf install   libv4l-devel -y
sudo dnf install   libexif-devel -y
sudo dnf install   intltool -y
sudo dnf install   cups-devel -y
sudo dnf install   xorg-x11-drv-wacom-devel -y
sudo dnf install   pam-devel -y
sudo dnf install   libcap-devel -y
sudo dnf install   libpng-devel -y
sudo dnf install   exempi-devel -y
sudo dnf install   libyaml-devel -y
sudo dnf install   cairo-devel -y
sudo dnf install   libxklavier-devel -y
sudo dnf install   gmime-devel -y
sudo dnf install   mesa-libGL-devel -y
sudo dnf install   xorg-x11-xtrans-devel -y
sudo dnf install   libpwquality-devel -y
sudo dnf install   python3-devel -y
sudo dnf install   cmake -y
sudo dnf install   libXtst-devel -y
sudo dnf install   llvm-devel -y
sudo dnf install   rubypick -y
sudo dnf install   hyphen-devel -y
sudo dnf install   libpinyin-devel -y
sudo dnf install   alsa-lib-devel -y
sudo dnf install   libXdamage-devel -y
sudo dnf install   libXrender-devel -y
sudo dnf install   gperf -y
sudo dnf install   libjpeg-turbo-devel -y
sudo dnf install   fontconfig-devel -y
sudo dnf install   libgcrypt-devel -y
sudo dnf install   lcms2-devel -y
sudo dnf install   anthy-devel -y
sudo dnf install   mesa-libGLES-devel -y
sudo dnf install   libXcomposite-devel -y
sudo dnf install   libusbx-devel -y
sudo dnf install   libtiff-devel -y
sudo dnf install   startup-notification-devel -y
sudo dnf install   libxslt-devel -y
sudo dnf install   dbus-devel -y
sudo dnf install   ragel -y
sudo dnf install   libdmapsharing-devel -y
sudo dnf install   libicu-devel -y
sudo dnf install   libnice-devel -y
sudo dnf install   xmlto -y
sudo dnf install   libX11-devel -y
sudo dnf install   libdvdread-devel -y
sudo dnf install   libXext-devel -y
sudo dnf install   libXi-devel -y
sudo dnf install   sqlite-devel -y
sudo dnf install   taglib-devel -y
sudo dnf install   libatasmart-devel -y
sudo dnf install   iso-codes-devel -y
sudo dnf install   libhangul-devel -y
sudo dnf install   libevdev-devel -y
sudo dnf install   dbus-glib-devel -y
sudo dnf install   xorg-x11-util-macros -y
sudo dnf install   webkitgtk4-devel -y
sudo dnf install   wireless-tools-devel -y
sudo dnf install   libsmbclient-devel -y
sudo dnf install   p11-kit-devel -y
sudo dnf install   libvpx-devel -y
sudo dnf install   libacl-devel -y
sudo dnf install   libepoxy-devel -y
sudo dnf install   libndp-devel -y
sudo dnf install   avahi-gobject-devel -y
sudo dnf install   libtool-ltdl-devel -y
sudo dnf install   bluez-libs-devel -y
sudo dnf install   libXinerama-devel -y
sudo dnf install   mozjs24-devel -y
sudo dnf install   readline-devel -y
sudo dnf install   texinfo -y
sudo dnf install   libXft-devel -y
sudo dnf install   libdrm-devel -y
sudo dnf install   ppp-devel -y
sudo dnf install   libXrandr-devel -y
sudo dnf install   nss-devel -y
sudo dnf install   mpfr-devel -y
sudo dnf install   libXfixes-devel -y
sudo dnf install   wavpack-devel -y
sudo dnf install   freetype-devel -y
sudo dnf install   libproxy-devel -y
sudo dnf install   libical-devel -y
sudo dnf install   zlib-devel -y
sudo dnf install   libxkbfile-devel -y
sudo dnf install   libxcb-devel -y
sudo dnf install   libSM-devel -y
sudo dnf install   libcanberra-devel -y
sudo dnf install   libarchive-devel -y
sudo dnf install   python-devel -y
sudo dnf install   poppler-glib-devel -y
sudo dnf install   mesa-libwayland-egl-devel -y
sudo dnf install   libgudev-devel -y
sudo dnf install   libwebp-devel -y
sudo dnf install   webkitgtk3-devel -y
sudo dnf install   xorg-x11-proto-devel -y
sudo dnf install   enchant-devel -y
sudo dnf install   systemd-devel -y
sudo dnf install   polkit-devel -y
sudo dnf install   libnl3-devel -y
sudo dnf install   json-c-devel -y
sudo dnf install   libsndfile-devel -y
sudo dnf install   libmusicbrainz5-devel -y
sudo dnf install   bison -y
sudo dnf install   libdb-devel -y
sudo dnf install   mtdev-devel -y
sudo dnf install   sbc-devel -y
sudo dnf install   libxml2-devel -y
sudo dnf install   gnutls-devel -y
sudo dnf install   mesa-libgbm-devel -y
sudo dnf install   plymouth-devel -y
sudo dnf install   krb5-devel -y
sudo dnf install   libgphoto2-devel -y
sudo dnf install   xkeyboard-config-devel -y
sudo dnf install   libXcursor-devel -y
sudo dnf install   liboauth-devel -y
sudo dnf install   ibgphoto2 -y
sudo dnf install   gbm -y
sudo dnf install   plymouth -y
sudo dnf install   rdflib -y
sudo dnf install   plymouth-devel -y
sudo dnf install   libgphoto2-devel -y
sudo dnf install   mesa-libgbm-devel -y

